<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-head-line">CẬP NHẬT THÔNG TIN HÌNH ẢNH</h1>
                <h1 class="page-subhead-line">CẬP NHẬT TỰ ĐỘNG ẢNH ĐẠI DIỆN VÀ ẢNH BÌA</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        CẬP NHẬT ẢNH ĐẠI DIỆN
                    </div>
                    <div class="panel-body">
                        <form role="form" id="frm_post">
                            <div class="form-group">
                                <label>Chọn Tài Khoản:</label>
                                <select class="form-control" id="account_select" name="account_select">
                                    <option value="">Tất cả</option>
                                    {% if list != null %}
                                        {% for index,item in list %}
                                            <option value="{{item.id}}">{{item.user_id}} - {{item.full_name}}</option>
                                        {% endfor  %}
                                    {% endif  %}
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="file" id="image_select_picture" name="image_select_picture[]" multiple>
                            </div>
                            <button type="button" class="btn btn-info" id="update_picture">CẬP NHẬT</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        CẬP NHẬT ẢNH BÌA
                    </div>
                    <div class="panel-body">
                        <form role="form" id="frm_post">
                            <div class="form-group">
                                <label>Chọn Tài Khoản:</label>
                                <select class="form-control" id="account_select" name="account_select">
                                    <option value="-1"></option>
                                    <option value="">Tất cả</option>
                                    {% if list != null %}
                                        {% for index,item in list %}
                                            <option value="{{item.id}}">{{item.user_id}} - {{item.full_name}}</option>
                                        {% endfor  %}
                                    {% endif  %}
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="file" id="image_select_cover" name="image_select_cover[]" multiple>
                            </div>
                            <button type="button" class="btn btn-info" id="update_cover">CẬP NHẬT</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /. PAGE INNER  -->
</div>
<script>
    $(function() {
        $('#update_picture').click(function(){
            Base_ajax.ok_cancel_box('Thực hiện xử lý này ?',function(){
                    var formData = new FormData();
                    if( $('#image_select_picture')[0].files.length > 0 ){
                        for (i = 0; i < $('#image_select_picture')[0].files.length; i++) {
                            formData.append('image_select_'+i,$('#image_select_picture')[0].files[i] );
                        }
                        formData.append('account_select',$('#account_select').val() );
                        $.ajax({
                            type: "POST",
                            url: "<%$smarty.const.ACW_BASE_URL%>profiles/updatePicture",
                            data: formData,
                            dataType: 'json',
                            cache : false,
                            contentType: false,
                            processData: false,
                            beforeSend: function(){
                                Base_ajax.loading(true);
                            },
                            success: function(data) {
                                Base_ajax.loading(false);
                                Base_ajax.message_box('Xong');
                            }
                        });
                    }else{
                        Base_ajax.message_box_error('Loi');
                    }
                }
            );
        });
        $('#update_cover').click(function(){
            Base_ajax.ok_cancel_box('Thực hiện xử lý này ?',function(){
                    var formData = new FormData();
                    if( $('#image_select_cover')[0].files.length > 0 ){
                        for (i = 0; i < $('#image_select_cover')[0].files.length; i++) {
                            formData.append('image_select_'+i,$('#image_select_cover')[0].files[i] );
                        }
                        formData.append('account_select',$('#account_select').val() );
                        $.ajax({
                            type: "POST",
                            url: "<%$smarty.const.ACW_BASE_URL%>profiles/updateCover",
                            data: formData,
                            dataType: 'json',
                            cache : false,
                            contentType: false,
                            processData: false,
                            beforeSend: function(){
                                Base_ajax.loading(true);
                            },
                            success: function(data) {
                                Base_ajax.loading(false);
                                Base_ajax.message_box('Xong');
                            }
                        });
                    }else{
                        Base_ajax.message_box_error('Loi');
                    }
                }
            );
        });
    });
</script>