<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-head-line">THÔNG TIN TOKEN</h1>
                <h1 class="page-subhead-line">Quản lý thông tin danh sách token</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Danh Sách Token
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <button id="exec_update" type="button" class="btn btn-info">Cập Nhật</button>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Email</th>
                                    <th>Mật Khẩu</th>
                                    <th>UID</th>
                                    <th>Họ Tên</th>
                                    <th>Tổng Số Bạn</th>
                                    <th>Sử Dụng</th>
                                    <th>Kiểm Tra Số Bạn</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% if tokenInfo != null %}
	                                {% for index,item in tokenInfo %}
	                                <tr>
	                                    <td>{{index+1}}</td>
	                                    <td>{{item['user']}}</td>
	                                    <td>{{item['pass']}}</td>
	                                    <td><a target="_blank" href="https://www.facebook.com/{{item['user_id']}}">{{item['user_id']}}</a></td>
	                                    <td>{{item['full_name']}}</td>
	                                    <td><label id="lbl_count_{{item['user_id']}}">-</label>/5000</td>
	                                    <td align="center">
	                                    	<input id="info_flg_{{item['m_token_id']}}" class="checkbox_info" type="checkbox" value="1" {% if item['info_status'] == 1 %} checked="checked" {% endif  %}/>
	                                    </td>
	                                    <td align="center">
	                                    	<button id="btn_friends_{{item['user_id']}}" type="button" class="btn btn-info button_getfriends">Kiểm Tra</button>
	                                    </td>
	                                </tr>
                                	{% endfor  %}
                                {% endif  %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /. PAGE INNER  -->
</div>
<script>
$(function() {
	$('.checkbox_info').change(function() {
		$('.checkbox_info').attr('disabled','disabled');
		var info_flg = 0;
		var chk_id = $(this).attr('id');
		var ids = chk_id.split('_');
		if ($(this).is(':checked')) {
			info_flg = 1;
		}
		
		var html_ajax = new Base_ajax("json");
		html_ajax.done_func = function(data) {
			if(data.status == 'OK'){
				Base_ajax.message_box('Xong');
			}
			else{
				Base_ajax.message_box_error('Loi');
			}
			$('.checkbox_info').removeAttr('disabled');
		};
		
		html_ajax.connect("POST", "Tokeninfo/updateinfoflg", 
				{
					'm_token_id':ids[2],
					'info_status':info_flg
				}
		);
	});
	
	$(document).off("click", ".button_getfriends");
	$(document).on("click", ".button_getfriends", function () {
		$('.button_getfriends').attr('disabled','disabled');
		var chk_id = $(this).attr('id');
		var ids = chk_id.split('_');
		
		var html_ajax = new Base_ajax("json");
		html_ajax.done_func = function(data) {
			if(data.status == 'OK'){
				$("#lbl_count_"+ids[2]).html(data.friends);
				Base_ajax.message_box('Xong');
			}
			else{
				$("#lbl_count_"+ids[2]).html('Error');
				Base_ajax.message_box_error('Loi');
			}
			$('.button_getfriends').removeAttr('disabled');
		};
		
		html_ajax.connect("POST", "Tokeninfo/checkfriends", 
				{
					'uid':ids[2]
				}
		);
	});
	
});
</script>