<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-head-line">THÔNG TIN TOKEN</h1>
                <h1 class="page-subhead-line">Quản lý thông tin danh sách token</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        Danh Sách Token
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <button id="exec_update" type="button" class="btn btn-info">Cập Nhật</button>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Email</th>
                                    <th>Mật Khẩu</th>
                                    <th>UID</th>
                                    <th>Họ Tên</th>
                                    <th>Tổng Số Bạn</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% if tokenInfo != null %}
	                                {% for index,item in tokenInfo %}
	                                <tr>
	                                    <td>{{index+1}}</td>
	                                    <td>{{item['user']}}</td>
	                                    <td>{{item['pass']}}</td>
	                                    <td><a target="_blank" href="https://www.facebook.com/{{item['user_id']}}">{{item['user_id']}}</a></td>
	                                    <td>{{item['full_name']}}</td>
	                                    <td><label>{{item['friends_count']}}</label>/5000</td>
	                                </tr>
                                	{% endfor  %}
                                {% endif  %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /. PAGE INNER  -->
</div>