<style type="text/css">
@keyframes lds-ring {
  0% {
    transform: rotate(0)
  }
  100% {
    transform: rotate(360deg)
  }
}
.lds-ring > div{
  position: absolute;
  top: 25%;
  left: 25%;
  width: 50%;
  height: 50%;
  border-radius: 50%;
  border: 5px solid #9edafe;
  border-color: #9edafe transparent transparent transparent;
  animation: lds-ring 1.5s cubic-bezier(0.5,0,0.5,1) infinite;
}
.lds-ring > div:nth-child(2) {
  animation-delay: .195s;
}
.lds-ring > div:nth-child(3) {
  animation-delay: .39s;
}
.lds-ring > div:nth-child(4) {
  animation-delay: .585s;
}
.loading_screen
{   
    height: 100%;
    width: 100%;
    position: fixed;
    z-index: 999;
    left: 0;
    top: 0;
    background-color: rgb(220,220,220);
    background-color: rgba(220,220,220, 0.8);
    overflow-x: hidden;
    overflow-y: hidden;
    display:none;
}
.message_dialog{
	min-width: 10px;
	min-height: 10px;
	max-width: 100px;
	max-height: 100px;
	/*background-color: gray;*/
	position: absolute;
	top:0;
	bottom: 0;
	left: 0;
	right: 0;
	margin: auto;
	border-style:solid ; 
}
.loading_dialog{
	min-width: 10px;
	min-height: 10px;
	max-width: 100px;
	max-height: 100px;
	/*background-color: blue;*/
	position: absolute;
	top:0;
	bottom: 0;
	left: 0;
	right: 0;
	margin: auto;
}
/* -------------------------------- 
xpopup 
-------------------------------- */
.img-replace {
  /* replace text with an image */
  display: inline-block;
  overflow: hidden;
  text-indent: 100%;
  color: transparent;
  white-space: nowrap;
}
.cd-popup {
  position: fixed;
  left: 0;
  top: 0;
  height: 100%;
  width: 100%;
  background-color: rgba(94, 110, 141, 0.9);
  opacity: 0;
  visibility: hidden;
  -webkit-transition: opacity 0.3s 0s, visibility 0s 0.3s;
  -moz-transition: opacity 0.3s 0s, visibility 0s 0.3s;
  transition: opacity 0.3s 0s, visibility 0s 0.3s;
  z-index: 999;
}
.cd-popup.is-visible {
  opacity: 1;
  visibility: visible;
  -webkit-transition: opacity 0.3s 0s, visibility 0s 0s;
  -moz-transition: opacity 0.3s 0s, visibility 0s 0s;
  transition: opacity 0.3s 0s, visibility 0s 0s;
}

.cd-popup-container {
  position: relative;
  width: 90%;
  max-width: 400px;
  margin: 4em auto;
  background: #FFF;
  border-radius: .25em .25em .4em .4em;
  text-align: center;
  box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
  -webkit-transform: translateY(-40px);
  -moz-transform: translateY(-40px);
  -ms-transform: translateY(-40px);
  -o-transform: translateY(-40px);
  transform: translateY(-40px);
  /* Force Hardware Acceleration in WebKit */
  -webkit-backface-visibility: hidden;
  -webkit-transition-property: -webkit-transform;
  -moz-transition-property: -moz-transform;
  transition-property: transform;
  -webkit-transition-duration: 0.3s;
  -moz-transition-duration: 0.3s;
  transition-duration: 0.3s;
}
.cd-popup-container p {
  padding: 3em 1em;
}
.cd-buttons-ok,.cd-buttons-error,
.cd-buttons{
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
.cd-popup-container .cd-buttons-error:after,
.cd-popup-container .cd-buttons-ok:after,
.cd-popup-container .cd-buttons:after {
  content: "";
  display: table;
  clear: both;
}

.cd-popup-container .cd-buttons li {
  float: left;
  width: 50%;
  list-style: none;
}
.cd-popup-container .cd-buttons-error li,
.cd-popup-container .cd-buttons-ok li {
  float: left;
  width: 100%;
  list-style: none;
}
.cd-popup-container .cd-buttons-ok a {
  display: block;
  height: 60px;
  line-height: 60px;
  text-transform: uppercase;
  color: #FFF;
  -webkit-transition: background-color 0.2s;
  -moz-transition: background-color 0.2s;
  transition: background-color 0.2s;
}
.cd-popup-container .cd-buttons-error a {
  display: block;
  height: 60px;
  line-height: 60px;
  text-transform: uppercase;
  color: #FFF;
  -webkit-transition: background-color 0.2s;
  -moz-transition: background-color 0.2s;
  transition: background-color 0.2s;
}
.cd-popup-container .cd-buttons-ok li:first-child a {
  background: #fc7169;
  border-radius: 0 0 .25em .25em;
}
.no-touch .cd-popup-container .cd-buttons-ok li:first-child a:hover {
  background-color: #fc8982;
}
.cd-popup-container .cd-buttons-error li:first-child a {
  background: #fc7169;
  border-radius: 0 0 .25em .25em;
}
.no-touch .cd-popup-container .cd-buttons-error li:first-child a:hover {
  background-color: #fc8982;
}
.cd-popup-container .cd-buttons a {
  display: block;
  height: 60px;
  line-height: 60px;
  text-transform: uppercase;
  color: #FFF;
  -webkit-transition: background-color 0.2s;
  -moz-transition: background-color 0.2s;
  transition: background-color 0.2s;
}
.cd-popup-container .cd-buttons li:first-child a {
  background: #fc7169;
  border-radius: 0 0 0 .25em;
}
.no-touch .cd-popup-container .cd-buttons li:first-child a:hover {
  background-color: #fc8982;
}
.cd-popup-container .cd-buttons li:last-child a {
  background: #b6bece;
  border-radius: 0 0 .25em 0;
}
.no-touch .cd-popup-container .cd-buttons li:last-child a:hover {
  background-color: #c5ccd8;
}
.cd-popup-container .cd-popup-close {
  position: absolute;
  top: 8px;
  right: 8px;
  width: 30px;
  height: 30px;
}
.cd-popup-container .cd-popup-close::before, .cd-popup-container .cd-popup-close::after {
  content: '';
  position: absolute;
  top: 12px;
  width: 14px;
  height: 3px;
  background-color: #8f9cb5;
}
.cd-popup-container .cd-popup-close::before {
  -webkit-transform: rotate(45deg);
  -moz-transform: rotate(45deg);
  -ms-transform: rotate(45deg);
  -o-transform: rotate(45deg);
  transform: rotate(45deg);
  left: 8px;
}
.cd-popup-container .cd-popup-close::after {
  -webkit-transform: rotate(-45deg);
  -moz-transform: rotate(-45deg);
  -ms-transform: rotate(-45deg);
  -o-transform: rotate(-45deg);
  transform: rotate(-45deg);
  right: 8px;
}
.is-visible .cd-popup-container {
  -webkit-transform: translateY(0);
  -moz-transform: translateY(0);
  -ms-transform: translateY(0);
  -o-transform: translateY(0);
  transform: translateY(0);
}
.cd-popup-message{
	padding-top: 50px;
	padding-bottom: 50px;
	padding-left:10px;
	padding-right:10px;
}
@media only screen and (min-width: 1170px) {
  .cd-popup-container {
    margin: 8em auto;
  }
}
</style>
<script type="text/javascript">
    function Base_ajax() {
        this.initialize.apply(this, arguments);
    }
    
    Base_ajax.prototype.initialize = function(data_type) {
        this.ajax_option = {
    		cache: false,
    		dataType: data_type,
    		statusCode: {
    			401 : function () {
    				//Edit start LIXD-614 TinVNIT 12022016
    				//$('#modal_message').dialog('close');
    				//Base_ajax.sesstion_err_msg();
    				//Edit end LIXD-614 TinVNIT 12022016
    			}
    		}
    	};
    };
    
    Base_ajax.prototype.always_func = function (data){
    	//alert(111);
    };
    Base_ajax.prototype.done_func = function (data){
    	//alert(111);
    };
    Base_ajax.prototype.fail_func = function (data) {
    	/*if(data.status == 0){
    		if(data.responseText == ""){

    		}else{
                Base_ajax.message_box_error(data.responseText);
    		}
    	}else{

    	}*/
    	Base_ajax.message_box_error(data.responseText);
    };
    
    Base_ajax.prototype.connect = function (action_type, ajax_url, ajax_data) {
    	var aa_this = this;
    	var opt =　this.ajax_option;
    	Base_ajax.loading(true);
    	opt.type =  action_type;
    	opt.url = {{ config.application.baseUri }} + ajax_url;
    	if (ajax_data) {
    		opt.data = ajax_data;
    	} else if (opt.data) {
    		delete opt.data;
    	}
    	$.ajax(opt)
    		.always(function (data) {
    			Base_ajax.loading(false);
    			aa_this.always_func(data);
    		})	// alwaysを一番先に実行
    		.done(aa_this.done_func)
    		.fail(aa_this.fail_func);
    };
    
    Base_ajax.message_box = function (msg,ok_func,cancel_func) {
    	$('.cd-popup-message').html(msg);
    	
    	event.preventDefault();
    	$('.cd-buttons').hide();
    	$('.cd-buttons-error').hide();
    	$('.cd-buttons-ok').show();
    	$('.cd-popup').addClass('is-visible');
    	
    	$('.cd-popup').off('click');
    	$('.cd-popup').on('click', function(event){
    		if( $(event.target).is('.cd-popup-close') || $(event.target).is('.cd-popup') ) {
    			event.preventDefault();
    			$(this).removeClass('is-visible');
    			if (cancel_func) {
    				cancel_func();
    			}
    		}
    	});
    	
    	$('#confirm_ok').off('click');
    	$('#confirm_ok').on('click', function(event){
    		event.preventDefault();
    		$('.cd-popup').removeClass('is-visible');
    		if (ok_func) {
    			ok_func();
    		}
    	});
    };
    
    Base_ajax.ok_cancel_box = function (msg, ok_func, cancel_func) {
    	$('.cd-popup-message').html(msg);
    	
    	event.preventDefault();
    	$('.cd-buttons').show();
    	$('.cd-buttons-ok').hide();
    	$('.cd-buttons-error').hide();
    	$('.cd-popup').addClass('is-visible');
    	
    	$('.cd-popup').off('click');
    	$('.cd-popup').on('click', function(event){
    		if( $(event.target).is('.cd-popup-close') || $(event.target).is('.cd-popup') ) {
    			event.preventDefault();
    			$(this).removeClass('is-visible');
    			if (cancel_func) {
    				cancel_func();
    			}
    		}
    	});
    	
    	$('#confirm_yes').off('click');
    	$('#confirm_yes').on('click', function(event){
    		event.preventDefault();
    		$('.cd-popup').removeClass('is-visible');
    		if (ok_func) {
    			ok_func();
    		}
    	});
    	
    	$('#confirm_no').off('click');
    	$('#confirm_no').on('click', function(event){
    		event.preventDefault();
    		$('.cd-popup').removeClass('is-visible');
    		if (cancel_func) {
    			cancel_func();
    		}
    	});
    	
    	
    };
    
    Base_ajax.message_box_error = function (msg,ok_func,cancel_func) {
    	$('.cd-popup-message').html(msg);
    	
    	event.preventDefault();
    	$('.cd-buttons').hide();
    	$('.cd-buttons-error').show();
    	$('.cd-buttons-ok').hide();
    	$('.cd-popup').addClass('is-visible');
    	
    	$('.cd-popup').off('click');
    	$('.cd-popup').on('click', function(event){
    		if( $(event.target).is('.cd-popup-close') || $(event.target).is('.cd-popup') ) {
    			event.preventDefault();
    			$(this).removeClass('is-visible');
    			if (cancel_func) {
    				cancel_func();
    			}
    		}
    	});
    	
    	$('#confirm_error').off('click');
    	$('#confirm_error').on('click', function(event){
    		event.preventDefault();
    		$('.cd-popup').removeClass('is-visible');
    		if (ok_func) {
    			ok_func();
    		}
    	});
    };
    
    Base_ajax.loading = function (flag) {
    	if (flag) {
    		$("#loading_screen").show();
    	} else {
    		$("#loading_screen").hide();
    	}
    };
    
</script>
<div id="loading_screen" class="loading_screen">
    <div class="loading_dialog center">
        <!--Preloader-->
        <div class="lds-css">
            <div class="lds-ring" style="width:100%;height:100%">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
            </div>
        </div>
    </div>
</div>
<div class="cd-popup" role="alert">
    <div class="cd-popup-container">
        <div class="cd-popup-message">
            Are you sure you want to delete this element?
        </div>
        <ul class="cd-buttons">
            <li><a id="confirm_yes" href="#">ĐỒNG Ý</a></li>
            <li><a id="confirm_no" href="#">QUAY LẠI</a></li>
        </ul>
        <ul class="cd-buttons-ok">
            <li><a id="confirm_ok" href="#">THÀNH CÔNG</a></li>
        </ul>
        <ul class="cd-buttons-error">
            <li><a id="confirm_error" href="#">ĐÓNG</a></li>
        </ul>
        <a href="#" class="cd-popup-close img-replace">Close</a>
    </div>
    <!-- cd-popup-container -->
</div>
<!-- cd-popup -->