 <div class="row text-center " style="padding-top:100px;">
    <div class="col-md-12">
        <img src="" />
    </div>
</div>
<div class="row ">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-10 col-xs-offset-1">
        <div class="panel-body">
            <form role="form" id="frm_login">
                <hr />
                <h5>Đăng Nhập Vào Hệ Thống Facebook</h5>
                <br />
                <div class="form-group input-group">
                    <span class="input-group-addon"><i class="fa fa-tag"  ></i></span>
                    <input id="user_id" name="user_id" type="text" class="form-control" placeholder="Tài Khoản" />
                </div>
                <div class="form-group input-group">
                    <span class="input-group-addon"><i class="fa fa-lock"  ></i></span>
                    <input id="passwd" name="passwd" type="password" class="form-control"  placeholder="Mật Khẩu" />
                </div>
                <button id="login" type="button" class="btn btn-info">Đăng Nhập</button>
            </form>
        </div>
    </div>
</div>
 <script>
     $(function() {
         $('#login').click(function(){
             if($('#user_id').val() != '' && $('#passwd').val() != ''){
                 var html_ajax = new Base_ajax("json");
                 html_ajax.done_func = function(data) {
                     if(data.error_msg != ''){
                         Base_ajax.message_box_error(data.error_msg);
                     }
                     else{
					 	if(data.homelink != ''){
							window.location = data.homelink;
						}
					 }
                 };
                 var data = $("form#frm_login").serializeArray();
                 html_ajax.connect("POST", "login/auth", data);
             }
             else{
                 Base_ajax.message_box_error('Cần Nhập Thông Tin Đăng Nhập!');
             }
         });
     });
 </script>