<?php echo $this->tag->getDocType();?>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Phalcon PHP Framework</title>
        <?php $this->assets->outputCss() ?>
        <?php $this->assets->outputJs(); ?>
    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar navbar-default navbar-cls-top " role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html">COMPANY NAME</a>
                </div>

                <div class="header-right">

                    <a href="message-task.html" class="btn btn-info" title="New Message"><b>30 </b><i class="fa fa-envelope-o fa-2x"></i></a>
                    <a href="message-task.html" class="btn btn-primary" title="New Task"><b>40 </b><i class="fa fa-bars fa-2x"></i></a>
                    <a href="login.html" class="btn btn-danger" title="Logout"><i class="fa fa-exclamation-circle fa-2x"></i></a>


                </div>
            </nav>

            <!-Menu Left->
            <nav class="navbar-default navbar-side" role="navigation">
                <div class="sidebar-collapse">
                    <ul class="nav" id="main-menu">
                        <li>
                            <?= $this->tag->linkTo(["index", "<i class=\"fa fa-dashboard \"></i>Dashboard"]); ?>
                        </li>
                        <li>
                            <?= $this->tag->linkTo(["token", "<i class=\"fa fa-square-o \"></i>Thêm Tài Khoản"]); ?>
                        </li>
                        <li>
                            <?= $this->tag->linkTo(["tokeninfo", "<i class=\"fa fa-dashboard \"></i>Quản Lý Tài Khoản"]); ?>
                        </li>
                        <li>
                            <?= $this->tag->linkTo(["friends", "<i class=\"fa fa-square-o \"></i>Tự Động Kết Bạn"]); ?>
                        </li>
                        <li>
                            <?= $this->tag->linkTo(["getuid", "<i class=\"fa fa-square-o \"></i>Quét UID"]); ?>
                        </li>
                        <li>
                            <?= $this->tag->linkTo(["postfeed", "<i class=\"fa fa-square-o \"></i>Đăng Bài Hàng Loạt"]); ?>
                        </li>
                        <li>
                            <?= $this->tag->linkTo(["profiles", "<i class=\"fa fa-square-o \"></i>Cập Nhật Hình Ảnh Tài Khoản"]); ?>
                        </li>
                    </ul>

                </div>
            </nav>
            <?php echo $this->getContent(); ?>
            <div id="footer-sec">
                &copy; 2014 YourCompany | Design By : <a href="http://www.binarytheme.com/" target="_blank">BinaryTheme.com</a>
            </div>
        </div>
    </body>
</html>
<?php $this->partial("shared/base_ajax");?>